version: "3.8"
services:
  user-service:
    build:
      context: ./user_services
    ports:
      - "3000:3000"
    environment:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: db
      JWT_SECRET: "${JWT_KEY}"
    depends_on:
      - db
    networks:
      - blog-network

  blog-service:
    build:
      context: ./blog_services
    ports:
      - "4000:4000"
    environment:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: db
    depends_on:
      - db
    networks:
      - blog-network

  comment-service:
    build:
      context: ./comment_services
    ports:
      - "5000:5000"
    environment:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: db
    depends_on:
      - db
    networks:
      - blog-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  db_data:
